function s(
  handle,
  name,
  tagline,
  description,
  url,
  platform,
  country,
  category,
  amount,
  clicks,
  daysAgo,
  raises = [],
  socials = [],
) {
  return {
    handle,
    name,
    tagline,
    description,
    url,
    platform,
    country,
    category,
    amount,
    clicks,
    daysAgo,
    raises,
    socials,
  };
}

const r = (extra, hoursAgo) => [{ extra, hoursAgo }];

export const SEED_CREATORS = [
  // —— Streamers España
  s("@ibai", "Ibai", "la velada y el KOI", "Ibai Llanos. El streamer más seguido de Twitch. Charla, eventos y La Velada del Año.", "https://twitch.tv/ibai", "twitch", "ES", "streaming", 25000, 184000, 48, r(2200, 6), [{ platform: "youtube", url: "https://youtube.com/@ibai" }]),
  s("@auronplay", "AuronPlay", "sarcasmo en directo", "Raúl Álvarez. Humor, Minecraft y uno de los canales en español más grandes de Twitch.", "https://twitch.tv/auronplay", "twitch", "ES", "streaming", 23200, 162000, 47, r(1800, 14), [{ platform: "youtube", url: "https://youtube.com/@auronplay" }]),
  s("@rubius", "Rubius", "el rubius", "ElRubius. YouTube clásico, Twitch y el directo que no necesita presentación.", "https://twitch.tv/rubius", "twitch", "ES", "streaming", 21800, 171000, 45, r(1600, 9)),
  s("@thegrefg", "TheGrefg", "skins y saiyans", "David Cánovas. Fortnite, Team Heretics y récords de audiencia en Twitch.", "https://twitch.tv/thegrefg", "twitch", "ES", "gaming", 19800, 98000, 44, r(1400, 20), [{ platform: "youtube", url: "https://youtube.com/@TheGrefg" }]),
  s("@illojuan", "IlloJuan", "el directo de las tardes", "Juan. Just chatting, Hunt y una de las medias más altas de España en 2026.", "https://twitch.tv/illojuan", "twitch", "ES", "streaming", 17200, 74000, 30, r(2100, 5)),
  s("@elxokas", "ElXokas", "política, poker y caos", "Joaquín. Opinión, poker y el stream que se convierte en trending.", "https://twitch.tv/elxokas", "twitch", "ES", "streaming", 12800, 61000, 41, r(400, 18)),
  s("@perxitaa", "Perxitaa", "el late del reino", "Jaume. Charla, eventos y uno de los pilares del streaming español.", "https://twitch.tv/perxitaa", "twitch", "ES", "streaming", 9600, 42000, 38, r(300, 22)),
  s("@folagorlives", "Folagor", "el capitán", "Folagor03. Pokémon, comunidad y años de directo.", "https://twitch.tv/folagorlives", "twitch", "ES", "gaming", 7800, 28000, 36),
  s("@knekro", "KNekro", "el grindeo eterno", "Horas, variedad y una de las cadenas más constantes de Twitch ES.", "https://twitch.tv/knekro", "twitch", "ES", "gaming", 7400, 22000, 21, r(200, 11)),
  s("@peereira7", "Peereira7", "horas y horas", "Pereira. El maratón hecho streamer.", "https://twitch.tv/peereira7", "twitch", "ES", "streaming", 7100, 19000, 12, r(500, 7)),
  s("@mixwell", "Mixwell", "valorant en castellano", "Oscar. Pro de Valorant y directo de élite.", "https://twitch.tv/mixwell", "twitch", "ES", "gaming", 6800, 16000, 19),
  s("@baitybait", "BaityBait", "el análisis", "Baity. Gaming, opinión y comunidad.", "https://twitch.tv/baitybait", "twitch", "ES", "gaming", 6400, 15000, 16),
  s("@djmariio", "DjMaRiiO", "FIFA y palos", "Mario. El rey del FIFA en español.", "https://twitch.tv/djmariio", "twitch", "ES", "deportes", 8200, 34000, 28, r(250, 30)),
  s("@gerardromero", "Gerard Romero", "el vestuario", "Fútbol, rumores y el late de la Liga.", "https://twitch.tv/gerardromero", "twitch", "ES", "deportes", 6900, 21000, 14, r(180, 9)),
  s("@cristinini", "Cristinini", "esports y plató", "Cristina. Presentación, esports y directo.", "https://twitch.tv/cristinini", "twitch", "ES", "streaming", 5200, 18000, 33),
  s("@biyin_", "Biyín", "charla sin filtro", "Biyín. Just chatting y uno de los nombres históricos del circuito.", "https://twitch.tv/biyin_", "twitch", "ES", "streaming", 4100, 12000, 40),
  s("@ampeterby7", "Ampeter", "kick y caos", "Ampeterby7. Variedad, Kick y el directo imprevisible.", "https://kick.com/ampeterby7", "kick", "ES", "streaming", 4800, 14000, 25),
  s("@vegetta777", "Vegetta777", "el constructor", "Minecraft, series y una de las audiencias históricas de YouTube ES.", "https://youtube.com/@vegetta777", "youtube", "ES", "gaming", 8800, 54000, 50),
  s("@willyrex", "Willyrex", "el dúo eterno", "Guillermo. YouTube, series y el otro pilar de Minecraft ES.", "https://youtube.com/@Willyrex", "youtube", "ES", "gaming", 8400, 49000, 49),
  s("@alexelcapo", "Alexelcapo", "souls y paliza", "Alex. FromSoftware, reto y directo veterano.", "https://twitch.tv/alexelcapo", "twitch", "ES", "gaming", 5600, 17000, 27),
  s("@luzu", "Luzu", "el retorno", "LuzuGames. Variedad, humor y el comeback.", "https://twitch.tv/luzu", "twitch", "ES", "streaming", 5000, 20000, 22),
  s("@revenant", "Reven", "el duelo", "Revenant. FPS, duelos y comunidad hardcore.", "https://twitch.tv/revenant", "twitch", "ES", "gaming", 4300, 11000, 18),
  s("@nexxuz", "Nexxuz", "kick ranked", "Nexxuz. Kick, ranked y el grind.", "https://kick.com/nexxuz", "kick", "ES", "gaming", 3900, 9000, 11),
  s("@mangelrogel", "Mangel", "el otro de youtube", "Mangel. Sketch, series y YouTube clásico.", "https://youtube.com/@MangelRogel", "youtube", "ES", "humor", 3600, 16000, 46),
  s("@zonagemelos", "Zona Gemelos", "el dúo de kick", "Gemelos. Kick, charla y audiencia joven.", "https://kick.com/zonagemelos", "kick", "ES", "streaming", 3400, 8000, 9),

  // —— TikTok / influencers España
  s("@lolalolita", "Lola Lolita", "el for you español", "Lola Lolita. TikTok, marcas y una de las audiencias más grandes de España.", "https://tiktok.com/@lolalolita", "tiktok", "ES", "tiktok", 7600, 88000, 20, r(400, 12)),
  s("@benjikrol", "Benji Krol", "35 millones de fyp", "Benji Krol. Uno de los tiktokers con más seguidores de España.", "https://tiktok.com/@benjikrol", "tiktok", "ES", "tiktok", 7200, 41000, 24),
  s("@naimdarrechi", "Naim Darrechi", "el playback", "Naim. Trends, música y audiencia masiva en TikTok.", "https://tiktok.com/@naimdarrechi", "tiktok", "ES", "tiktok", 5800, 36000, 26),
  s("@judiitharias", "Judith Arias", "glow y trends", "Judith. Belleza, GRWM y TikTok España.", "https://tiktok.com/@judiitharias", "tiktok", "ES", "belleza", 4700, 29000, 15),
  s("@yosoyplex", "YoSoyPlex", "humor en 15s", "Plex. Sketches, tendencias y una de las ER más altas.", "https://tiktok.com/@yosoyplex", "tiktok", "ES", "humor", 5400, 52000, 13, r(220, 8)),
  s("@dulceida", "Dulceida", "la pionera", "Aida Domènech. Moda, orgullo y una de las primeras grandes influencers ES.", "https://instagram.com/dulceida", "instagram", "ES", "moda", 6200, 24000, 52),
  s("@mariapombo", "María Pombo", "lifestyle de pueblo", "María Pombo. Casa, familia y el feed que copian las marcas.", "https://instagram.com/mariapombo", "instagram", "ES", "lifestyle", 5100, 19000, 31),
  s("@paulagonu", "Paula Gonu", "el feed de siempre", "Paula Gonu. Lifestyle, viajes y una de las cuentas históricas.", "https://instagram.com/paulagonu", "instagram", "ES", "lifestyle", 3800, 14000, 42),
  s("@martaa_diiaz", "Marta Díaz", "el día a día", "Marta Díaz. TikTok e Instagram de vida cotidiana.", "https://tiktok.com/@martaa_diiaz", "tiktok", "ES", "lifestyle", 3500, 21000, 17),
  s("@skyandtami", "Sky & Tami", "la pareja de sevilla", "Sky y Tami. Dúo, trends y audiencia teen.", "https://tiktok.com/@skyandtami", "tiktok", "ES", "tiktok", 3300, 18000, 10),
  s("@marlucas", "Mar Lucas", "urban en vertical", "Mar Lucas. Música y TikTok.", "https://tiktok.com/@marlucas", "tiktok", "ES", "musica", 3100, 15000, 8),
  s("@itsnicolewallace", "Nicole Wallace", "actriz en el fyp", "Nicole Wallace. Series, lifestyle y TikTok.", "https://tiktok.com/@itsnicolewallace", "tiktok", "ES", "lifestyle", 3000, 22000, 7),
  s("@lolaindigo", "Lola Índigo", "el perreo con tesis", "Música, coreos y una de las artistas más cruzadas con TikTok.", "https://instagram.com/lolaindigo", "instagram", "ES", "musica", 6700, 33000, 29),
  s("@aitanax", "Aitana", "el pop que pega", "Aitana. Pop, escenarios y redes.", "https://instagram.com/aitanax", "instagram", "ES", "musica", 7300, 28000, 34),
  s("@rosalia", "Rosalía", "el motomami", "Rosalía. La artista española con más peso global. Motomami y el feed que manda.", "https://instagram.com/rosalia", "instagram", "ES", "musica", 18500, 96000, 55, r(900, 40)),

  // —— LATAM streamers
  s("@westcol", "WestCOL", "kick y la velada", "WestCOL. Colombia, Kick y picos de millones. El fenómeno LATAM del live.", "https://kick.com/westcol", "kick", "CO", "streaming", 16400, 67000, 23, r(1900, 4)),
  s("@juansguarnizo", "JuanSGuarnizo", "el presidente", "Juan Sebastián Guarnizo. Twitch, música y uno de los reyes de LATAM.", "https://twitch.tv/juansguarnizo", "twitch", "CO", "streaming", 14800, 58000, 35, r(700, 16)),
  s("@spreen", "Spreen", "el argentino", "Spreen. Minecraft, Squid Craft y una de las audiencias más fieles.", "https://twitch.tv/spreen", "twitch", "AR", "gaming", 12100, 44000, 27, r(500, 13)),
  s("@rivers_gg", "Rivers", "el late mexicano", "Rivers_gg. Charla, eventos y una de las medias más altas de LATAM.", "https://twitch.tv/rivers_gg", "twitch", "MX", "streaming", 11400, 39000, 18, r(800, 10)),
  s("@elmariana", "ElMariana", "el directo de méxico", "ElMariana. Just chatting y comunidad enorme.", "https://twitch.tv/elmariana", "twitch", "MX", "streaming", 9800, 36000, 15, r(450, 8)),
  s("@arigameplays", "AriGameplays", "la reina del rec room", "Ari. Twitch, eventos y una de las streamers más seguidas.", "https://twitch.tv/arigameplays", "twitch", "MX", "streaming", 8600, 31000, 32),
  s("@aldo_geo", "Aldo Geo", "el mexicano constante", "Aldo_geo. Horas, variedad y audiencia estable.", "https://twitch.tv/aldo_geo", "twitch", "MX", "streaming", 6100, 14000, 14),
  s("@roier", "Roier", "qsmp y el pingüino", "Roier. Minecraft, role y Twitch MX.", "https://twitch.tv/roier", "twitch", "MX", "gaming", 5900, 17000, 19),
  s("@quackity", "Quackity", "qsmp y el imperio", "Quackity. El puente MX–US. Eventos, SMP y Twitch.", "https://twitch.tv/quackity", "twitch", "MX", "streaming", 13200, 51000, 37, r(600, 25)),
  s("@martinciriook", "Martin Cirio", "el argentino que explota", "MartinCirioOk. Just chatting y una media disparada.", "https://twitch.tv/martinciriook", "twitch", "AR", "streaming", 10200, 12000, 6, r(1100, 3)),
  s("@davooxeneize", "Davoo Xeneize", "boca y kick", "Davoo. Fútbol, Kick y horas vistas de récord en Argentina.", "https://kick.com/davooxeneize", "kick", "AR", "deportes", 8900, 18000, 8, r(700, 5)),
  s("@lacobraaa", "La Cobra", "el otro de kick", "La Cobra. Fútbol argentino en directo.", "https://kick.com/lacobraaa", "kick", "AR", "deportes", 7700, 13000, 9),
  s("@mrstiven", "MrStiven", "chupistream", "MrStiven. Colombia, Kick y picos brutales.", "https://kick.com/mrstiven", "kick", "CO", "streaming", 8100, 16000, 11, r(350, 6)),
  s("@alofoke", "Alofoke", "el show del caribe", "Santiago Matías. Entrevistas, música urbana y picos de millón en YouTube/Kick.", "https://youtube.com/@Alofoke", "youtube", "DO", "podcast", 15600, 48000, 12, r(2400, 2)),

  // —— Influencers / YouTube LATAM
  s("@luisitocomunica", "Luisito Comunica", "el mundo en vlog", "Luis Arturo Villar. Viajes, marcas y el YouTube más grande de México.", "https://youtube.com/@LuisitoComunica", "youtube", "MX", "viajes", 14200, 72000, 53, r(500, 28)),
  s("@kimberly.loaiza", "Kimberly Loaiza", "el imperio", "Kimberly Loaiza. Música, familia y una de las cuentas más grandes de LATAM.", "https://instagram.com/kimberly.loaiza", "instagram", "MX", "musica", 13800, 81000, 39, r(400, 15)),
  s("@yuyacst", "Yuya", "belleza que dura", "Mariand Castrejón. Makeup, marca propia y el YouTube que abrió el camino.", "https://instagram.com/yuyacst", "instagram", "MX", "belleza", 9100, 26000, 54),
  s("@juandediospantoja", "Juan de Dios Pantoja", "el dinámico", "Juan de Dios. YouTube familiar y retos.", "https://youtube.com/@JuandeDiosPantoja", "youtube", "MX", "lifestyle", 8700, 35000, 28),
  s("@domelipa", "Domelipa", "el fyp mexicano", "Domelipa. TikTok, baile y una de las audiencias teen más grandes.", "https://tiktok.com/@domelipa", "tiktok", "MX", "baile", 9400, 64000, 16, r(300, 9)),
  s("@juanpazurita", "Juanpa Zurita", "el mexicano global", "Juanpa. Lifestyle, marcas y Hollywood-adjacent.", "https://instagram.com/juanpazurita", "instagram", "MX", "lifestyle", 9900, 30000, 43),
  s("@lospolinesios", "Los Polinesios", "la familia", "Los Polinesios. YouTube familiar mexicano de toda la vida.", "https://youtube.com/@LosPolinesios", "youtube", "MX", "familia", 7000, 27000, 51),
  s("@werevertumorro", "Werevertumorro", "el humor de siempre", "Werever. Sketch, opinión y YouTube MX clásico.", "https://youtube.com/@Werevertumorro", "youtube", "MX", "humor", 4500, 19000, 48),
  s("@fernanfloo", "Fernanfloo", "el salvadoreño", "Fernanfloo. Gaming, humor y una de las audiencias históricas de YouTube.", "https://youtube.com/@Fernanfloo", "youtube", "SV", "gaming", 8000, 58000, 56),
  s("@drossrotzank", "Dross", "el terror", "DrossRotzank. Terror, lore y YouTube en venezolano.", "https://youtube.com/@DrossRotzank", "youtube", "VE", "youtube", 6600, 24000, 57),
  s("@holasoygerman", "HolaSoyGerman", "el chileno", "Germán Garmendia. El YouTube que marcó una generación.", "https://youtube.com/@HolaSoyGerman", "youtube", "CL", "humor", 7500, 41000, 58),
  s("@enchufetv", "EnchufeTV", "el sketch ecuatoriano", "EnchufeTV. Comedia, sketches y el sketch latino de referencia.", "https://youtube.com/@EnchufeTV", "youtube", "EC", "humor", 4900, 22000, 44),
  s("@lelepons", "Lele Pons", "la venezolana global", "Lele Pons. Humor, música y una de las latinas más grandes de Instagram.", "https://instagram.com/lelepons", "instagram", "VE", "humor", 9200, 37000, 40),
  s("@badabun", "Badabun", "el medio", "Badabun. Entretenimiento, rumores y YouTube masivo.", "https://youtube.com/@Badabun", "youtube", "MX", "noticias", 4200, 20000, 33),
  s("@laliendra", "La Liendra", "el colombiano", "La Liendra. Entretenimiento, redes y Colombia.", "https://instagram.com/laliendra", "instagram", "CO", "lifestyle", 4000, 15000, 21),
  s("@kikanieto", "Kika Nieto", "beauty CO", "Kika Nieto. Belleza y lifestyle colombiano.", "https://instagram.com/kikanieto", "instagram", "CO", "belleza", 3200, 11000, 24),
  s("@karolg", "Karol G", "la bichota", "Karol G. El pop urbano colombiano que manda en el mundo.", "https://instagram.com/karolg", "instagram", "CO", "musica", 16800, 77000, 36, r(800, 19)),
  s("@feid", "Feid", "ferxxo", "Feid. Reggaetón, ferxxo y el mainstream colombiano.", "https://instagram.com/feid", "instagram", "CO", "musica", 10500, 29000, 18),
  s("@bizarrap", "Bizarrap", "las bzrp", "Bizarrap. Las sesiones que rompen internet.", "https://instagram.com/bizarrap", "instagram", "AR", "musica", 11900, 34000, 22, r(350, 17)),
  s("@duki", "Duki", "el rapero", "Duki. Trap argentino y el superestrella de una generación.", "https://instagram.com/duki", "instagram", "AR", "musica", 8300, 21000, 20),
  s("@badbunnypr", "Bad Bunny", "el conejo", "Bad Bunny. El fenómeno global. Puerto Rico manda.", "https://instagram.com/badbunnypr", "instagram", "PR", "musica", 21000, 102000, 59, r(1200, 33)),
  s("@peso_pluma", "Peso Pluma", "corridos tumbados", "Peso Pluma. El regional mexicano que se hizo global.", "https://instagram.com/peso_pluma", "instagram", "MX", "musica", 10100, 26000, 14),
  s("@Shakira", "Shakira", "caderas y tick tock", "Shakira. La más grande. Barranquilla, el mundo y el FYP.", "https://instagram.com/shakira", "instagram", "CO", "musica", 19200, 88000, 60, r(600, 45)),

  // —— Nichos extra (ficticios, abajo del ranking)
  s("@lunavarela", "Luna Varela", "glow sin filtro", "Makeup artist en CDMX. Tutoriales de piel real y collabs de skincare.", "https://instagram.com/lunavarela", "instagram", "MX", "belleza", 840, 1840, 16, r(40, 11)),
  s("@cafeycodigo", "Café y código", "dev en español", "Tutoriales de web e IA. Sin bootcamp milagroso.", "https://youtube.com/@cafeycodigo", "youtube", "GT", "tech", 240, 1100, 6),
  s("@opositaconluz", "Luz Oposita", "temario sin drama", "Oposiciones y técnicas de estudio.", "https://youtube.com/@opositaconluz", "youtube", "ES", "educacion", 190, 1400, 9),
  s("@talentandino", "Talent Andino", "el roster del Pacífico", "Management en PE, EC y CO.", "https://talentandino.com", "instagram", "PE", "agencias", 160, 640, 11),
];
